### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-usa#17]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Dependencies

https://github.com/OCA/account-financial-tools/issues/551
- [x] account_reversal

https://github.com/OCA/account-payment/issues/161
- [x] account_check_printing_report_base
- [x] account_payment_batch_process
- [x] account_payment_credit_card
- [x] partner_aging

https://github.com/OCA/account-invoice-reporting/issues/63
- [x] partner_time_to_pay

https://github.com/OCA/account-reconcile/issues/186
- [x] account_banking_reconciliation

# Modules to migrate

- [x] l10n_us_form_1099 by @max3903 in #21
- [ ] l10n_us_uom_profile
- [x] l10n_us_check_writing_address by @Sudarshan1607 in #25 and @murtuzasaleh in #31
- [x] l10n_us_account_profile by @Sudarshan1607 in #26 and @murtuzasaleh in #32
