### ISSUE TITLE
l10n_us_account_profile - US Accounting

### ISSUE THREAD

**Issue by max3903** [OCA/l10n-usa#5]
# US Accounting Profile

This module provides all the dependencies, data, parameters and configuration panel to have Odoo as an accounting software ready for US accountants and equivalent to local solutions like Quickbooks.

# 0.0.1

#7 

- [x] account_due_list

# 0.0.2

- [x] account_reversal: https://github.com/OCA/account-financial-tools/pull/445
- [x] account_payment_batch_process: https://github.com/OCA/account-payment/pull/138
- [x] account_payment_credit_card: https://github.com/OCA/account-payment/pull/139
- [x] partner_aging: https://github.com/OCA/account-payment/pull/136 by @Sudarshan1607 
- [x] partner_daytopay: https://github.com/OCA/account-invoice-reporting/pull/53 by @bodedra
- [x] account_check_printing_report_base: https://github.com/OCA/account-payment/pull/147 by @smangukiya
- [x] l10n_us_check_writing_address: https://github.com/OCA/l10n-usa/pull/8 by @Sudarshan1607 
- [x] l10n_us_form_1099: #13 by @wujenne2
- [x] l10n_us_account_profile: #11 by @Sudarshan1607 

# 0.0.3

- [x] account_banking_reconciliation: https://github.com/OCA/bank-statement-reconcile/pull/174 by @bodedra
- [ ] partner_financial_risk: https://github.com/OCA/partner-contact/pull/360
- [ ] partner_sale_risk: https://github.com/OCA/partner-contact/issues/309
- [ ] partner_stock_risk: https://github.com/OCA/partner-contact/issues/309
- [ ] l10n_us_account_profile:

**Comment by JordiBForgeFlow** [comment]
Where is l10n_us_check_printing?

We implemented check printing in the DLT103 (a common standard in the US) format here:
https://github.com/OCA/account-payment/pull/121

**Comment by max3903** [comment]
@jbeficent It's not public yet, but we plan to share it.

**Comment by JordiBForgeFlow** [comment]
@max3903 What is the point now, if there's already the PR stated above?

**Comment by max3903** [comment]
@jbeficent Let me discuss with my team. I don't have all the info yet. That's why I started this thread.

**Comment by JordiBForgeFlow** [comment]
@max3903 In any case it will be good to compare both approaches and go for the best or a mix of both ;)

**Comment by JordiBForgeFlow** [comment]
I think that the following are relevant:
* account_due_list
* account_due_list_days_overdue
* account_due_list_aging_comments

To some extent I anticipate that these would be duplicates with 'partner_aging'.

You at URSA also have an interesting module 'account_fstr' that is handy. Are you planning to publish it?

**Comment by max3903** [comment]
@jbeficent Not sure. We will need to contact @enapps and @nazarii first:
https://github.com/enapps/account_fstr

**Comment by max3903** [comment]
@jbeficent account_due_list_aging_comments and partner_aging could be merged into a module with:

- the columns from account_due_list_aging_comments
- the comments from account_due_list_aging_comments
- the computation of age and amount when grouping from partner_aging
- the computation from any date from partner_aging

partner_aging is also integrated with a batch payment module that we have. It allows you to pick the invoices from the aging and generates the payments.

**Comment by max3903** [comment]
@jbeficent Do you have any plan to migrate account_due_list_aging_comments from version 8 to 10? 

Considering partner_aging is already migrated to version 10, do you have any problem if I include partner_aging first and once account_due_list_aging_comments is migrated, we merge the 2 together?

**Comment by JordiBForgeFlow** [comment]
@max3903 we have proposed a PR to v9: https://github.com/OCA/account-payment/pull/124

As for partner_aging, see the function that provides information about days due for the AR and AP:
https://github.com/OCA/account-payment/tree/8.0/account_due_list_days_overdue
https://github.com/OCA/account-payment/pull/123

We would need to review your partner_aging before deciding the next steps. Can you send it as a PR or provide a link?

**Comment by max3903** [comment]
@jbeficent 

l10n_us_check_writing_address:
https://github.com/OCA/l10n-usa/pull/8

partner_aging:
https://github.com/OCA/account-payment/pull/136

**Comment by max3903** [comment]
Ping @lasley @stephankeller

**Comment by stephankeller** [comment]
@max3903 Thanks, we will try to review as soon as possible.

**Comment by max3903** [comment]
Ping @bistaray, @raycollazo
