### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-usa#88]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] account_banking_ach_base - By @JordiBForgeFlow - #128
- [ ] l10n_us_form_1099 - By @lk-eska - #92
- [x] l10n_us_gaap - By @lk-eska - #91
- [x] partner_usps_address_validation - By @Urvisha-OSI - #102
